name: Solar system app workflow
on:
  workflow_dispatch: 
  push:
    branches: 
      - main
      - 'feature/*'

jobs:
    unit_testing:
        name: apply unit test on code
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the Repository
          uses: actions/checkout@v4

        - name: Setup node js version  - 18
          uses: actions/setup-node@v3

        - name: Install dependencies
          run: npm install

        - name: Run unit test
          run: npm test