name: Solar system app workflow
on:
  workflow_dispatch: 
  push:
    branches: 
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
    unit_testing:
        strategy:
          matrix:
            nodejs_versions: [18, 19, 20]
            os: [ubuntu-latest, macos-latest]
            exclude:
              - nodejs_versions: 18
                os: macos-latest

        
        name: apply unit test on code
        runs-on: ${{matrix.os}}
        steps:
        - name: Checkout the Repository
          uses: actions/checkout@v4

        - name: Setup node js version  - ${{matrix.nodejs_versions}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_versions}}

        - name: Install dependencies
          run: npm install

        - name: Run unit test
          run: npm test

        - name: Upload artifact 
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result-${{ matrix.nodejs_versions }}-${{ matrix.os }}
            path: test-results.xml

    code_coverage:
        name: apply unit test on code
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the Repository
          uses: actions/checkout@v4

        - name: Setup node js version  
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install dependencies
          run: npm install

        - name: Run code coverage
          run: npm run coverage
          continue-on-error: true

        - name: Upload artifact 
          uses: actions/upload-artifact@v4
          with:
            name: Coverage-Report
            path: coverage
            retention-days: 3